### ISSUE TITLE
Unexpected responseTo in response

### ISSUE THREAD

**Issue by johnnyzz** [pharo-nosql/mongotalk#9] opened 2016-09-07 19:46 UTC
Hi,
I have a code snippet that raises "Unexpected responseTo in response" Error.

``` smalltalk
| mongoCollection db root |
root := Mongo default open.
db := root databaseNamed: 'mongo-tests'.
"mongoCollection := db collectionAt: 'testCollection'."
mongoCollection := db addCollection: 'testCollection'.

mongoCollection add: ({ 'name' -> 'A' . 'score' -> 1 } asDictionary).
mongoCollection add: ({ 'name' -> 'B' . 'score' -> 2 } asDictionary).
mongoCollection add: ({ 'name' -> 'C' . 'score' -> 3 } asDictionary).

[
    mongoCollection do: [ :each | Notification signal ].
] on: Notification do: [ :ex | ex resume ]. "OK - works"

[
    mongoCollection do: [ :each | Notification signal ].
] on: Notification do: [ :ex |  
    "intercepted by exception"
    mongoCollection do: [ :each | ]. "-> trigger ERROR"
].

[
    mongoCollection do: [ :each | Notification signal ].
] on: Notification do: [ :ex | ex resume ]. "-> ERROR - should work"

"FIX: root close. root open."
```

If you run the first block which iterates through the Mongo collection, all works well.
But the Error is raised, if run the second block. After that, everything is broken, and you can't even run _anything_ again without the Error. Closing the connection and opening it again fixes this.
Something is wrong in `MongoCursor>>execute`, the current instance of `ReplyOperation` is somehow invalid.
I think there are unread documents, if the read process is interrupted, and then the connection is in invalid state...

**Comment by tinchodias** [comment] 2016-10-14 16:09
Hi @johnnyzz I could reproduce the error. After a quick debug I couldn't find the problem but I would look at the mongodb's documentation related to `QueryOperation` (executed in` root cursorQuery: query`).

**Comment by johnnyzz** [comment] 2016-10-14 22:30
Hi @tinchodias I believe, the cursor needs to _always_ read all requested objects before executing another query with new cursor. Even if the exception interrupts the reading process. But neither `#ensure:` nor connection pooling would work here, the connection should be first somehow locked for writing with active cursor to prevent multiple concurrent reads/writes. Anyway I still don't know a proper solution.

**Comment by tinchodias** [comment] 2016-10-15 01:30
Ah, it makes sense. Maybe the second query can either:
- "automatically" ensure the stream is empty (flush it) or 
- "manually" signal an error because it's not possible to start a new query while the stream isn't empty, and the user can decide to flush the stream.
These are not all possibilities, of course... Does this make any sense? I never went into the level of the Mongo's stream. 

Do you get into this scenario because of an "$err" in the query that signals an error?

**Comment by johnnyzz** [comment] 2016-10-15 11:33
The cause of this error for me was some Exception raised from my custom `#doBlock:` passed to  `MongoQuery` & reusing the connection somewhere else again. Usually the block is only collecting received objects by default, so this is working well. But the case with "$err" should be considered too I think, but is it mostly signalled at the beginning, not in the middle of the reading of the stream.

**Comment by noha** [comment] 2017-02-06 11:16
There is one problem and two reasons for it. The communication towars mongo is done on a stream. It only works if one writes completely or reads completely from it before another one can use it. The reason this could be a probem is either if two processes write at the same time to it or if there is an error in between, e.g. a debugger

**Comment by johnnyzz** [comment] 2017-03-28 16:54
Hi, in the meantime, I'm always opening new connection, and closing it regardless the error occurs or not. But it's kind of a hack, since MongoTalk doesn't support connection pooling. It would help a lot.

**Comment by noha** [comment] 2017-03-29 08:40
In my opinion we should move the connection pooling from voyage to mongotalk

**Comment by noha** [comment] 2019-04-18 10:43
Can we close this issue?

**Comment by tinchodias** [comment] 2019-04-18 16:11
I think we can close it.

I agree that mongotalk could implement pooling like other drivers. Mongodb proposes drivers to satisfy [this spec](https://docs.mongodb.com/ecosystem/drivers/specs/), where there are sub-specs related to pooling:
* [Connection Monitoring and Pooling](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst)
* [SDAM](https://github.com/mongodb/specifications/tree/master/source/server-discovery-and-monitoring)

**Closed** 2019-04-18 16:29 UTC
